check for inotify before trying to run. otherwise the conditional command will just execute

diff --git a/inotifyrun b/inotifyrun
--- a/inotifyrun
+++ b/inotifyrun
@@ -22,6 +22,8 @@
 
 # man inotifywait for more info
 
+test ! $(command -v inotifywait) \
+	&& { printf "inotifywait: command not found\n" ; exit 1 ; }
 while true; do
 	inotifywait -e close_write "$1"
 	if [ -z $2 ]; then
